var RecipeConstants = {
  ALL_RECIPES_RECEIVED: "ALL_RECIPES_RECEIVED",
  SINGLE_RECIPE_RECEIVED: "SINGLE_RECIPE_RECEIVED",
  ALL_INGREDIENTS_RECEIVED: "ALL_INGREDIENTS_RECEIVED",
  SINGLE_INGREDIENT_RECEIVED: "SINGLE_INGREDIENT_RECEIVED",
  ALL_STEPS_RECEIVED: "ALL_STEPS_RECEIVED",
  SINGLE_STEP_RECEIVED: "SINGLE_STEP_RECEIVED",
  ALL_NOTES_RECEIVED: "ALL_NOTES_RECEIVED",
  SINGLE_NOTE_RECEIVED: "SINGLE_NOTE_RECEIVED"
};

module.exports = RecipeConstants;
