# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea4c4cab3a617c98af55a6a7197f9123c77cefd00868f2b05d83facdd795b5f5882acadc0c820801af5613fbece7dff6923d135113a79ea1c5a0f2e62cbd5e6

test:
  secret_key_base: f14a4a80be224014b8ddad77a534f297600b1412d562123ad4a14d6710a9411916f2d3a882fd9386891675a25dae9132d64fb114ab248970b36316b0ff76e8f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
